Insert into scores (question_id,question_content,options,real_section,value) values ('2','¿Cuentan con un inventario de todo el hardware?','SI','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('2','¿Cuentan con un inventario de todo el hardware?','NO','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('2','¿Cuentan con un inventario de todo el hardware?','EN PROCESO','1','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('3','¿Está automatizado este inventario?','SI','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('3','¿Está automatizado este inventario?','NO','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('3','¿Está automatizado este inventario?','EN PARTE','1','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('4','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('4','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','1','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('4','¿Con qué frecuencia se actualiza?','ANUALMENTE','1','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('4','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('5','¿Existe un procedimiento que establezca el responsable del inventario, a quién reporta, qué se registra y cada cuánto se revisa?','SI','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('5','¿Existe un procedimiento que establezca el responsable del inventario, a quién reporta, qué se registra y cada cuánto se revisa?','NO','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('5','¿Existe un procedimiento que establezca el responsable del inventario, a quién reporta, qué se registra y cada cuánto se revisa?','EN PROCESO','1','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('6','¿Existe un procedimiento que indica qué hacer ante la conexión de un activo no autorizado?','SI','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('6','¿Existe un procedimiento que indica qué hacer ante la conexión de un activo no autorizado?','NO','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('6','¿Existe un procedimiento que indica qué hacer ante la conexión de un activo no autorizado?','EN PROCESO','1','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('7','¿Qué se hace ante la conexión de un equipo que no pertenece al inventario de hardware?','Deniega la conexión','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('7','¿Qué se hace ante la conexión de un equipo que no pertenece al inventario de hardware?','Se mantiene en cuarentena','1','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('7','¿Qué se hace ante la conexión de un equipo que no pertenece al inventario de hardware?','Otro','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('8','¿El inventario de hardware ha sido aprobado por la gerencia general?','SI','1','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('8','¿El inventario de hardware ha sido aprobado por la gerencia general?','NO','1','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('8','¿El inventario de hardware ha sido aprobado por la gerencia general?','EN PROCESO','1','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('9','¿Cuentan con un inventario del software instalado en las máquinas de su red?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('9','¿Cuentan con un inventario del software instalado en las máquinas de su red?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('9','¿Cuentan con un inventario del software instalado en las máquinas de su red?','EN PROCESO','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('10','¿Este inventario está automatizado?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('10','¿Este inventario está automatizado?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('10','¿Este inventario está automatizado?','EN PROCESO','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('11','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('11','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('11','¿Con qué frecuencia se actualiza?','ANUALMENTE','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('11','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('12','¿Existe un procedimiento que establezca el responsable del inventario, a quién reporta, qué se registra y cada cuánto se revisa?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('12','¿Existe un procedimiento que establezca el responsable del inventario, a quién reporta, qué se registra y cada cuánto se revisa?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('12','¿Existe un procedimiento que establezca el responsable del inventario, a quién reporta, qué se registra y cada cuánto se revisa?','EN PROCESO','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('13','¿Tiene incluido en su inventario de software los firmware de routers, switch y firewall de su red?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('13','¿Tiene incluido en su inventario de software los firmware de routers, switch y firewall de su red?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('14','¿Todo el software tiene soporte?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('14','¿Todo el software tiene soporte?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('14','¿Todo el software tiene soporte?','PARCIALMENTE','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('15','En caso de contar con software sin soporte ¿Se cuenta con un plan de mitigación de riesgos?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('15','En caso de contar con software sin soporte ¿Se cuenta con un plan de mitigación de riesgos?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('15','En caso de contar con software sin soporte ¿Se cuenta con un plan de mitigación de riesgos?','PARCIALMENTE','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('16','¿Están actualizados los firmware de los routers, switchs y firewalls de su red?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('16','¿Están actualizados los firmware de los routers, switchs y firewalls de su red?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('17','¿Existe un procedimiento que indica qué hacer ante la presencia de un software no autorizado?','SI','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('17','¿Existe un procedimiento que indica qué hacer ante la presencia de un software no autorizado?','NO','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('17','¿Existe un procedimiento que indica qué hacer ante la presencia de un software no autorizado?','EN PROCESO','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('18','¿Qué se realiza ante un activo no autorizado?','DENIEGA INSTALACION','2','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('18','¿Qué se realiza ante un activo no autorizado?','SE MANTIENE EN CUARENTENA','2','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('18','¿Qué se realiza ante un activo no autorizado?','SE VALIDA EXCEPCIÓN','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('18','¿Qué se realiza ante un activo no autorizado?','NO APLICA','2','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('19','¿Cuentan con un proceso de gestión de información sensible?','SI','3','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('19','¿Cuentan con un proceso de gestión de información sensible?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('20','¿Este proceso está escrito?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('20','¿Este proceso está escrito?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('21','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','3','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('21','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('21','¿Con qué frecuencia se actualiza?','ANUALMENTE','3','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('21','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('22','¿Cuentan con un inventario de información sensible?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('22','¿Cuentan con un inventario de información sensible?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('22','¿Cuentan con un inventario de información sensible?','OTRO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('23','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','3','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('23','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','3','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('23','¿Con qué frecuencia se actualiza?','ANUALMENTE','3','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('23','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('24','¿Existe un proceso donde se describan los tiempos de retención de la información corporativa?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('24','¿Existe un proceso donde se describan los tiempos de retención de la información corporativa?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('25','¿Cuéntan con listas de control de acceso a la informacion?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('25','¿Cuéntan con listas de control de acceso a la informacion?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('25','¿Cuéntan con listas de control de acceso a la informacion?','OTRO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('26','¿Los usuarios cuentan con cuentas de acceso personal para acceder al sistema?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('26','¿Los usuarios cuentan con cuentas de acceso personal para acceder al sistema?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('26','¿Los usuarios cuentan con cuentas de acceso personal para acceder al sistema?','PARCIALMENTE','3','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('27','¿Los administradores de la red cuentan con un perfil propio en todos los equipos?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('27','¿Los administradores de la red cuentan con un perfil propio en todos los equipos?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('27','¿Los administradores de la red cuentan con un perfil propio en todos los equipos?','PARCIALMENTE','3','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('28','¿Este proceso está escrito?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('28','¿Este proceso está escrito?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('30','¿Está definido el tiempo de mantencion mínima/máxima de los archivos corporativos?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('30','¿Está definido el tiempo de mantencion mínima/máxima de los archivos corporativos?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('31','¿Este proceso está escrito?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('31','¿Este proceso está escrito?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('32','¿Se incluye en el proceso de gestión de información sensible este punto sobre la eliminación de información sensible?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('32','¿Se incluye en el proceso de gestión de información sensible este punto sobre la eliminación de información sensible?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('33','¿Existe un procedimiento para manejar el equipo de un empleado que ha dejado la compañía?','SI Y ESTÁ DOCUMENTADO','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('33','¿Existe un procedimiento para manejar el equipo de un empleado que ha dejado la compañía?','SI Y NO ESTÁ DOCUMENTADO','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('33','¿Existe un procedimiento para manejar el equipo de un empleado que ha dejado la compañía?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('34','¿Este proceso esta escrito?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('34','¿Este proceso esta escrito?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('35','¿Cuentan con listas de control de acceso a la informacion?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('35','¿Cuentan con listas de control de acceso a la informacion?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('35','¿Cuentan con listas de control de acceso a la informacion?','OTRO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('36','¿Cuentan los equipos con sistema de encriptacion activado?','SI','3','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('36','¿Cuentan los equipos con sistema de encriptacion activado?','NO','3','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('36','¿Cuentan los equipos con sistema de encriptacion activado?','ALGUNOS','3','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('37','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('37','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('38','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('38','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('39','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('39','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','4','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('39','¿Con qué frecuencia se actualiza?','ANUALMENTE','4','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('39','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('40','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('40','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('41','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('41','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('42','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('42','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','4','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('42','¿Con qué frecuencia se actualiza?','ANUALMENTE','4','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('42','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('43','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('43','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('44','¿Los equipos de la compañía cuenta con el bloqueo de sesión automático ante inactividad?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('44','¿Los equipos de la compañía cuenta con el bloqueo de sesión automático ante inactividad?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('45','¿Después de qué periodo de inactividad se bloquea?','(Minutos) 1','4','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('45','¿Después de qué periodo de inactividad se bloquea?','(Minutos) 5','4','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('45','¿Después de qué periodo de inactividad se bloquea?','(Minutos) 10','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('45','¿Después de qué periodo de inactividad se bloquea?','(Minutos) 15','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('45','¿Después de qué periodo de inactividad se bloquea?','(Minutos) OTRO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('46','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('46','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('47','¿Cuentan con firewall configurado?','SI','4','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('47','¿Cuentan con firewall configurado?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('49','¿Existe una regla default-deny que impide el tráfico excepto el de los servicios o puertos permitidos?','SI','4','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('49','¿Existe una regla default-deny que impide el tráfico excepto el de los servicios o puertos permitidos?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('49','¿Existe una regla default-deny que impide el tráfico excepto el de los servicios o puertos permitidos?','NO CUENTO CON ESA INFORMACIÓN','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('50','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('50','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('51','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conexiones?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('51','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conexiones?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('51','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conexiones?','NO CUENTO CON ESA INFORMACIÓN','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('52','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('52','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('53','¿Su página institucional utiliza certificado seguro (ssl o https)?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('53','¿Su página institucional utiliza certificado seguro (ssl o https)?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('54','¿Estas configuraciones están documentadas?','SI','4','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('54','¿Estas configuraciones están documentadas?','NO','4','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('56','¿Se cuenta con un inventario de todas las cuentas de acceso a la compañía?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('56','¿Se cuenta con un inventario de todas las cuentas de acceso a la compañía?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('57','¿Están estas restricciones documentadas?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('57','¿Están estas restricciones documentadas?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('58','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('58','¿Con qué frecuencia se actualiza?','AL MENOS UNA VEZ AL SEMESTRE','5','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('58','¿Con qué frecuencia se actualiza?','ANUALMENTE','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('58','¿Con qué frecuencia se actualiza?','NO SE ACTUALIZA','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('59','¿Está establecido el uso de contraseñas únicas por usuario?','SI','5','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('59','¿Está establecido el uso de contraseñas únicas por usuario?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('60','¿Cuentan con segundo factor de autentificacion en las cuentas?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('60','¿Cuentan con segundo factor de autentificacion en las cuentas?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('61','¿Las contraseñas utilizadas en la compañía tienen un minimo de 8 caracteres con+L39 2FA o 14 sin 2FA?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('61','¿Las contraseñas utilizadas en la compañía tienen un minimo de 8 caracteres con+L39 2FA o 14 sin 2FA?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('62','¿Estas configuraciones están documentadas?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('62','¿Estas configuraciones están documentadas?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('63','¿Las cuentas sin uso o durmientes son desactivadas despues de 45 días sin actividad?','SI','5','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('63','¿Las cuentas sin uso o durmientes son desactivadas despues de 45 días sin actividad?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('63','¿Las cuentas sin uso o durmientes son desactivadas despues de 45 días sin actividad?','OTRO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('64','¿Se ha denegado el privilegio de administrador, y además el acceso a la cuenta de administrador?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('64','¿Se ha denegado el privilegio de administrador, y además el acceso a la cuenta de administrador?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('65','¿Tienen todos los dispositivos de usuario configurada la cuenta administrador?','SI','5','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('65','¿Tienen todos los dispositivos de usuario configurada la cuenta administrador?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('66','El uso diario de los equipos ¿es realizado desde la cuenta de usuario solamente?','SI','5','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('66','El uso diario de los equipos ¿es realizado desde la cuenta de usuario solamente?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('67','¿Tienen los administradores de red una cuenta en todos los equipos?','SI','5','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('67','¿Tienen los administradores de red una cuenta en todos los equipos?','NO','5','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('68','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('68','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('68','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','OTRO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('69','¿Este proceso es automatizado?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('69','¿Este proceso es automatizado?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('70','¿Se sigue este proceso también para cambios de rol de un usuario?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('70','¿Se sigue este proceso también para cambios de rol de un usuario?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('71','¿Existe un proceso escrito de revocación de cuenta ante la salida de un usuario?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('71','¿Existe un proceso escrito de revocación de cuenta ante la salida de un usuario?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('71','¿Existe un proceso escrito de revocación de cuenta ante la salida de un usuario?','OTRO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('72','¿Este proceso es automatizado?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('72','¿Este proceso es automatizado?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('73','¿Se sigue este proceso también para cambios de rol de un usuario?','SI','6','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('73','¿Se sigue este proceso también para cambios de rol de un usuario?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('74','¿Existe esta configuración?','SI','6','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('74','¿Existe esta configuración?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('75','¿Está documentada?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('75','¿Está documentada?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('76','¿Existe esta configuración?','SI','6','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('76','¿Existe esta configuración?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('77','¿Está documentada?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('77','¿Está documentada?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('78','¿Existe esta configuración?','SI','6','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('78','¿Existe esta configuración?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('79','¿Está documentada?','SI','6','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('79','¿Está documentada?','NO','6','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('80','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('80','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('80','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','OTRO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('81','¿Este proceso es automatizado?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('81','¿Este proceso es automatizado?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('81','¿Este proceso es automatizado?','ALGUNOS','7','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('82','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('82','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','7','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('82','¿Cada cuanto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','7','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('82','¿Cada cuanto se revisa el proceso?','ANUALMENTE','7','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('82','¿Cada cuanto se revisa el proceso?','NO SE ACTUALIZA','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('83','¿Existe un proceso escrito de remediación de vulnerabilidades de la empresa?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('83','¿Existe un proceso escrito de remediación de vulnerabilidades de la empresa?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('83','¿Existe un proceso escrito de remediación de vulnerabilidades de la empresa?','OTRO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('84','¿Este proceso es automatizado?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('84','¿Este proceso es automatizado?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('85','¿Se ha realizado esta implementación?','CONTINUAMENTE','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('85','¿Se ha realizado esta implementación?','MENSUALMENTE','7','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('85','¿Se ha realizado esta implementación?','AL MENOS UNA VEZ AL SEMESTRE','7','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('85','¿Se ha realizado esta implementación?','ANUALMENTE','7','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('85','¿Se ha realizado esta implementación?','NO SE ACTUALIZA','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('86','¿Este proceso es automatizado?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('86','¿Este proceso es automatizado?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('87','¿Se ha realizado esta implementación?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('87','¿Se ha realizado esta implementación?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('88','¿Este proceso es automatizado?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('88','¿Este proceso es automatizado?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('89','¿Se ha realizado esta implementación?','SI','7','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('89','¿Se ha realizado esta implementación?','NO','7','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('90','¿Se ha realizado esta configuración?','SI','8','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('90','¿Se ha realizado esta configuración?','NO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('90','¿Se ha realizado esta configuración?','OTRO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('91','¿Existe un proceso escrito de gestión de logs de auditoria?','SI','8','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('91','¿Existe un proceso escrito de gestión de logs de auditoria?','NO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('91','¿Existe un proceso escrito de gestión de logs de auditoria?','OTRO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('92','¿Cada cuánto se revisa el proceso?','CONTINUAMENTE','8','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('92','¿Cada cuánto se revisa el proceso?','MENSUALMENTE','8','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('92','¿Cada cuánto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','8','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('92','¿Cada cuánto se revisa el proceso?','ANUALMENTE','8','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('92','¿Cada cuánto se revisa el proceso?','NO SE ACTUALIZA','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('93','¿Se ha realizado esta configuración?','SI','8','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('93','¿Se ha realizado esta configuración?','NO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('93','¿Se ha realizado esta configuración?','OTRO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('95','¿Se hacen backups de los logs?','SI','8','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('95','¿Se hacen backups de los logs?','NO','8','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('96','¿Es una política o directiva que se cumpla en un 100%?','SI','9','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('96','¿Es una política o directiva que se cumpla en un 100%?','NO','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('96','¿Es una política o directiva que se cumpla en un 100%?','OTRO','9','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('97','¿Está escrita esta política?','SI','9','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('97','¿Está escrita esta política?','NO','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('98','¿Cada cuánto se revisa el proceso?','CONTINUAMENTE','9','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('98','¿Cada cuánto se revisa el proceso?','MENSUALMENTE','9','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('98','¿Cada cuánto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','9','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('98','¿Cada cuánto se revisa el proceso?','ANUALMENTE','9','2');
Insert into scores (question_id,question_content,options,real_section,value) values ('98','¿Cada cuánto se revisa el proceso?','NO SE ACTUALIZA','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('99','¿Se ha realizado esta configuración?','SI','9','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('99','¿Se ha realizado esta configuración?','NO','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('99','¿Se ha realizado esta configuración?','OTRO','9','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('100','¿Existe un proceso escrito?','SI','9','15');
Insert into scores (question_id,question_content,options,real_section,value) values ('100','¿Existe un proceso escrito?','NO','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('101','¿Cada cuánto se revisa el proceso?','CONTINUAMENTE','9','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('101','¿Cada cuánto se revisa el proceso?','MENSUALMENTE','9','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('101','¿Cada cuánto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','9','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('101','¿Cada cuánto se revisa el proceso?','ANUALMENTE','9','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('101','¿Cada cuánto se revisa el proceso?','NO SE ACTUALIZA','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('102','¿Usa algun servicio de filtrado de DNS?','SI','9','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('102','¿Usa algun servicio de filtrado de DNS?','NO','9','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('102','¿Usa algun servicio de filtrado de DNS?','OTRO','9','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('103','¿Se ha realizado esta configuración?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('103','¿Se ha realizado esta configuración?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('103','¿Se ha realizado esta configuración?','OTRO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('105','¿Existe un proceso escrito que detalle la configuracion?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('105','¿Existe un proceso escrito que detalle la configuracion?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('106','¿Cada cuánto se revisa el proceso?','CONTINUAMENTE','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('106','¿Cada cuánto se revisa el proceso?','MENSUALMENTE','10','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('106','¿Cada cuánto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','10','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('106','¿Cada cuánto se revisa el proceso?','ANUALMENTE','10','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('106','¿Cada cuánto se revisa el proceso?','NO SE ACTUALIZA','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('107','¿Tiene su software anti-malware un sistema centralizado de administración?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('107','¿Tiene su software anti-malware un sistema centralizado de administración?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('108','¿Se ha realizado esta configuración?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('108','¿Se ha realizado esta configuración?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('108','¿Se ha realizado esta configuración?','OTRO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('109','¿Existe un proceso escrito que detalle la configuración?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('109','¿Existe un proceso escrito que detalle la configuración?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('110','¿Cada cuánto se revisa el proceso?','CONTINUAMENTE','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('110','¿Cada cuánto se revisa el proceso?','MENSUALMENTE','10','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('110','¿Cada cuánto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','10','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('110','¿Cada cuánto se revisa el proceso?','ANUALMENTE','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('110','¿Cada cuánto se revisa el proceso?','NO SE ACTUALIZA','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('111','¿Se ha realizado esta configuración?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('111','¿Se ha realizado esta configuración?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('111','¿Se ha realizado esta configuración?','OTRO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('112','¿Existe un proceso escrito que detalle la configuración?','SI','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('112','¿Existe un proceso escrito que detalle la configuración?','NO','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('113','¿Cada cuánto se revisa el proceso?','CONTINUAMENTE','10','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('113','¿Cada cuánto se revisa el proceso?','MENSUALMENTE','10','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('113','¿Cada cuánto se revisa el proceso?','AL MENOS UNA VEZ AL SEMESTRE','10','3');
Insert into scores (question_id,question_content,options,real_section,value) values ('113','¿Cada cuánto se revisa el proceso?','ANUALMENTE','10','1');
Insert into scores (question_id,question_content,options,real_section,value) values ('113','¿Cada cuánto se revisa el proceso?','NO SE ACTUALIZA','10','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('114','¿Cuentan con un proceso de recuperación ante desastres escrito?','SI','11','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('114','¿Cuentan con un proceso de recuperación ante desastres escrito?','NO','11','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('115','¿Todos los respaldos de las máquinas son automatizados?','SOLO ESTACIONES DE TRABAJO','11','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('115','¿Todos los respaldos de las máquinas son automatizados?','SOLO SERVIDORES','11','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('115','¿Todos los respaldos de las máquinas son automatizados?','AMBOS','11','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('115','¿Todos los respaldos de las máquinas son automatizados?','NINGUNO','11','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('116','¿Cada cuánto se realizan respaldos?','CONTINUAMENTE','11','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('116','¿Cada cuánto se realizan respaldos?','DIARIAMENTE','11','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('116','¿Cada cuánto se realizan respaldos?','SEMANALMENTE','11','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('116','¿Cada cuánto se realizan respaldos?','MENSUALMENTE','11','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('116','¿Cada cuánto se realizan respaldos?','NO SE ACTUALIZA','11','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('117','¿Cuentan con respaldo en todas las máquinas?','SI','11','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('117','¿Cuentan con respaldo en todas las máquinas?','NO','11','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('122','¿Cuentan con este punto?','SI','12','50');
Insert into scores (question_id,question_content,options,real_section,value) values ('122','¿Cuentan con este punto?','NO','12','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('122','¿Cuentan con este punto?','OTRO','12','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('123','¿Está documentado?','SI','12','50');
Insert into scores (question_id,question_content,options,real_section,value) values ('123','¿Está documentado?','NO','12','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('123','¿Está documentado?','OTRO','12','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('124','¿Se cuenta con un programa de concientización o capacitación en ciberseguridad?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('124','¿Se cuenta con un programa de concientización o capacitación en ciberseguridad?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('124','¿Se cuenta con un programa de concientización o capacitación en ciberseguridad?','NO APLICA','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('125','¿Está documentado?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('125','¿Está documentado?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('126','¿Se rigen por un programa/plan externo o es realizado internamente?','EXTERNO','14','20');
Insert into scores (question_id,question_content,options,real_section,value) values ('126','¿Se rigen por un programa/plan externo o es realizado internamente?','INTERNO','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('126','¿Se rigen por un programa/plan externo o es realizado internamente?','NO APLICA','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('128','¿El programa incluye este punto?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('128','¿El programa incluye este punto?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('129','¿El programa incluye este punto?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('129','¿El programa incluye este punto?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('130','¿El programa incluye este punto?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('130','¿El programa incluye este punto?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('131','¿El programa incluye este punto?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('131','¿El programa incluye este punto?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('132','¿El programa incluye este punto?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('132','¿El programa incluye este punto?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('133','¿El programa incluye este punto?','SI','14','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('133','¿El programa incluye este punto?','NO','14','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('134','¿El programa incluye este punto?','SI','15','30');
Insert into scores (question_id,question_content,options,real_section,value) values ('134','¿El programa incluye este punto?','NO','15','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('135','¿Cuentan con un inventario de proveedores de servicio?','SI','15','30');
Insert into scores (question_id,question_content,options,real_section,value) values ('135','¿Cuentan con un inventario de proveedores de servicio?','NO','15','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('135','¿Cuentan con un inventario de proveedores de servicio?','OTRO','15','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('136','¿Está documentado?','SI','15','40');
Insert into scores (question_id,question_content,options,real_section,value) values ('136','¿Está documentado?','NO','15','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('136','¿Está documentado?','OTRO','15','10');
Insert into scores (question_id,question_content,options,real_section,value) values ('137','¿Cuentan con personal designado?','SI','17','25');
Insert into scores (question_id,question_content,options,real_section,value) values ('137','¿Cuentan con personal designado?','NO','17','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('137','¿Cuentan con personal designado?','OTRO','17','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('138','¿Es conocido por toda la organización?','SI','17','25');
Insert into scores (question_id,question_content,options,real_section,value) values ('138','¿Es conocido por toda la organización?','NO','17','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('138','¿Es conocido por toda la organización?','OTRO','17','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('139','¿Cuenta toda la organización con esta información?', 'SI','17','25');
Insert into scores (question_id,question_content,options,real_section,value) values ('139','¿Cuenta toda la organización con esta información?', 'NO','17','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('139','¿Cuenta toda la organización con esta información?', 'OTRO','17','5');
Insert into scores (question_id,question_content,options,real_section,value) values ('140','¿Se cuenta con un procedimiento escrito que relate este punto?','SI','17','25');
Insert into scores (question_id,question_content,options,real_section,value) values ('140','¿Se cuenta con un procedimiento escrito que relate este punto?','NO','17','0');
Insert into scores (question_id,question_content,options,real_section,value) values ('140','¿Se cuenta con un procedimiento escrito que relate este punto?','OTRO','17','5');
