insert into scores (question_id,question_content) values ('1','¿Que prioridad le da la empresa a este punto de un 1 a 10?');				
insert into scores (question_id,question_content,options,value) values ('2','¿Cuentan con un inventario de todo el HW?','SI','2');	
insert into scores (question_id,question_content,options,value) values ('2','¿Cuentan con un inventario de todo el HW?','NO','0');	
insert into scores (question_id,question_content,options,value) values ('2','¿Cuentan con un inventario de todo el HW?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('3','¿Esta automatizado este inventario?','SI','2');
insert into scores (question_id,question_content,options,value) values ('3','¿Esta automatizado este inventario?','NO','0');
insert into scores (question_id,question_content,options,value) values ('3','¿Esta automatizado este inventario?','EN PARTE','1');		
insert into scores (question_id,question_content,options,value) values ('4','¿Con que frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('4','¿Con que frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');	
insert into scores (question_id,question_content,options,value) values ('4','¿Con que frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('4','¿Con que frecuencia se actualiza?','OTRO','1');	
insert into scores (question_id,question_content,options,value) values ('2','¿Existe un procedimiento que establezca el responsable del inventario, a quien reporta, qué se regiStra y cada cuánto se revisa?','SI','2');
insert into scores (question_id,question_content,options,value) values ('2','¿Existe un procedimiento que establezca el responsable del inventario, a quien reporta, qué se regiStra y cada cuánto se revisa?','NO','0');
insert into scores (question_id,question_content,options,value) values ('2','¿Existe un procedimiento que establezca el responsable del inventario, a quien reporta, qué se regiStra y cada cuánto se revisa?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('6','¿Existe un procedimiento qué indica qué hacer ante la conexión de un activo no autorizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('6','¿Existe un procedimiento qué indica qué hacer ante la conexión de un activo no autorizado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('6','¿Existe un procedimiento qué indica qué hacer ante la conexión de un activo no autorizado?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('7','¿Qué se realiza ante un activo no autorizado?','Deniega la conexion','2');
insert into scores (question_id,question_content,options,value) values ('7','¿Qué se realiza ante un activo no autorizado?','Se mantiene en cuarentena','2');
insert into scores (question_id,question_content,options,value) values ('7','¿Qué se realiza ante un activo no autorizado?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('8','¿El inventario de hardware ha sido aprobado por la direccion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('8','¿El inventario de hardware ha sido aprobado por la direccion?','NO','0');
insert into scores (question_id,question_content,options,value) values ('8','¿El inventario de hardware ha sido aprobado por la direccion?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('9','¿Cuéntan con un inventario del software instalado en las maquinas de su red?','SI','2');
insert into scores (question_id,question_content,options,value) values ('9','¿Cuéntan con un inventario del software instalado en las maquinas de su red?','NO','0');
insert into scores (question_id,question_content,options,value) values ('9','¿Cuéntan con un inventario del software instalado en las maquinas de su red?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('10','¿Este inventario está automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('10','¿Este inventario está automatizado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('10','¿Este inventario está automatizado?','EN PROCESO','1');	
insert into scores (question_id,question_content,options,value) values ('11','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('11','¿Con qué frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');
insert into scores (question_id,question_content,options,value) values ('11','¿Con qué frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('11','¿Con qué frecuencia se actualiza?','OTRO','1');
insert into scores (question_id,question_content,options,value) values ('12','¿Existe un procedimiento que establezca el responsable del inventario, a quien reporta, qué se registra y cada cuánto se revisa?','SI','2');
insert into scores (question_id,question_content,options,value) values ('12','¿Existe un procedimiento que establezca el responsable del inventario, a quien reporta, qué se registra y cada cuánto se revisa?','NO','0');
insert into scores (question_id,question_content,options,value) values ('12','¿Existe un procedimiento que establezca el responsable del inventario, a quien reporta, qué se registra y cada cuánto se revisa?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('13','¿Tiene incluido en su inventario de software los firmware de routers, switch y firewall de su red?','SI','2');
insert into scores (question_id,question_content,options,value) values ('13','¿Tiene incluido en su inventario de software los firmware de routers, switch y firewall de su red?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('14','¿Todo el software tiene soporte?','SI','2');
insert into scores (question_id,question_content,options,value) values ('14','¿Todo el software tiene soporte?','NO','0');
insert into scores (question_id,question_content,options,value) values ('14','¿Todo el software tiene soporte?','PARCIALMENTE','1');		
insert into scores (question_id,question_content,options,value) values ('12','En caso de contar con software sin soporte ¿Se cuenta con un plan de mitigación de riesgos?','SI','2');
insert into scores (question_id,question_content,options,value) values ('12','En caso de contar con software sin soporte ¿Se cuenta con un plan de mitigación de riesgos?','NO','0');
insert into scores (question_id,question_content,options,value) values ('12','En caso de contar con software sin soporte ¿Se cuenta con un plan de mitigación de riesgos?','PARCIALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('16','¿Estan actualizados los firmware de los routers, switchs y firewalls de su red?','SI','2');
insert into scores (question_id,question_content,options,value) values ('16','¿Estan actualizados los firmware de los routers, switchs y firewalls de su red?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('17','¿Existe un procedimiento qué indica qué hacer ante la presencia de un sofware no autorizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('17','¿Existe un procedimiento qué indica qué hacer ante la presencia de un sofware no autorizado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('17','¿Existe un procedimiento qué indica qué hacer ante la presencia de un sofware no autorizado?','EN PROCESO','1');		
insert into scores (question_id,question_content,options,value) values ('18','¿Qué se realiza ante un activo no autorizado?','DENIEGA INSTALACION','2');
insert into scores (question_id,question_content,options,value) values ('18','¿Qué se realiza ante un activo no autorizado?','SE MANTIENE EN CUARENTENA','2');
insert into scores (question_id,question_content,options,value) values ('18','¿Qué se realiza ante un activo no autorizado?','SE VALIDA EXCEPCIÓN','2');	
insert into scores (question_id,question_content,options,value) values ('19','¿Cuéntan con un proceso de gestión de información sensible?','SI','2');
insert into scores (question_id,question_content,options,value) values ('19','¿Cuéntan con un proceso de gestión de información sensible?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('20','¿Este proceso esta escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('20','¿Este proceso esta escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('21','¿Con que frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('21','¿Con que frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');
insert into scores (question_id,question_content,options,value) values ('21','¿Con que frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('21','¿Con que frecuencia se actualiza?','OTRO','0');	
insert into scores (question_id,question_content,options,value) values ('22','¿Cuentan con un inventario de información sensible?','SI','2');
insert into scores (question_id,question_content,options,value) values ('22','¿Cuentan con un inventario de información sensible?','NO','0');
insert into scores (question_id,question_content,options,value) values ('22','¿Cuentan con un inventario de información sensible?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('23','¿Con que frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('23','¿Con que frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');
insert into scores (question_id,question_content,options,value) values ('23','¿Con que frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('23','¿Con que frecuencia se actualiza?','OTRO','1');	
insert into scores (question_id,question_content,options,value) values ('24','¿Este proceso esta escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('24','¿Este proceso esta escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('22','¿Cuentan con listas de control de acceso a la informacion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('22','¿Cuentan con listas de control de acceso a la informacion?','NO','0');
insert into scores (question_id,question_content,options,value) values ('22','¿Cuentan con listas de control de acceso a la informacion?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('26','¿Los usuarios cuentan con cuentas de acceso personal para acceder al sistema?','SI','2');
insert into scores (question_id,question_content,options,value) values ('26','¿Los usuarios cuentan con cuentas de acceso personal para acceder al sistema?','NO','0');
insert into scores (question_id,question_content,options,value) values ('26','¿Los usuarios cuentan con cuentas de acceso personal para acceder al sistema?','PARCIALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('27','¿Los administradores de la red cuentan con un perfil propio en todos los equipos?','SI','2');
insert into scores (question_id,question_content,options,value) values ('27','¿Los administradores de la red cuentan con un perfil propio en todos los equipos?','NO','0');
insert into scores (question_id,question_content,options,value) values ('27','¿Los administradores de la red cuentan con un perfil propio en todos los equipos?','PARCIALMENTE','1');		
insert into scores (question_id,question_content,options,value) values ('28','¿Este proceso esta escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('28','¿Este proceso esta escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('29','¿Se incluye en el proceso de gestión de información sensible este punto,incluyendo retención minima y máxima?','SI','2');
insert into scores (question_id,question_content,options,value) values ('29','¿Se incluye en el proceso de gestión de información sensible este punto,incluyendo retención minima y máxima?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('30','¿Esta definido el tiempo de mantencion de los archivos corporativos?','SI','2');
insert into scores (question_id,question_content,options,value) values ('30','¿Esta definido el tiempo de mantencion de los archivos corporativos?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('31','¿Este proceso esta escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('31','¿Este proceso esta escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('32','¿Se incluye en el proceso de gestión de información sensible este punto sobre la eliminación de información sensible?','SI','2');
insert into scores (question_id,question_content,options,value) values ('32','¿Se incluye en el proceso de gestión de información sensible este punto sobre la eliminación de información sensible?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('33','¿Existe un procedimiento para manejar el equipo de un empleado que ha dejado la compañía?','SI','2');
insert into scores (question_id,question_content,options,value) values ('33','¿Existe un procedimiento para manejar el equipo de un empleado que ha dejado la compañía?','NO','0');
insert into scores (question_id,question_content,options,value) values ('33','¿Existe un procedimiento para manejar el equipo de un empleado que ha dejado la compañía?','NO ESCRITO','1');		
insert into scores (question_id,question_content,options,value) values ('34','¿Este proceso esta escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('34','¿Este proceso esta escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('32','¿Cuentan con listas de control de acceso a la informacion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('32','¿Cuentan con listas de control de acceso a la informacion?','NO','0');
insert into scores (question_id,question_content,options,value) values ('32','¿Cuentan con listas de control de acceso a la informacion?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('36','¿Cuentan los equipos con sistema de encriptacion activado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('36','¿Cuentan los equipos con sistema de encriptacion activado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('36','¿Cuentan los equipos con sistema de encriptacion activado?','ALGUNOS','1');		
insert into scores (question_id,question_content,options,value) values ('37','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('37','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('38','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('38','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('39','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('39','¿Con qué frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');
insert into scores (question_id,question_content,options,value) values ('39','¿Con qué frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('39','¿Con qué frecuencia se actualiza?','OTRO','1');
insert into scores (question_id,question_content,options,value) values ('40','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('40','¿Los equipos de la compañía cuenta con configuraciones seguras habilitadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('41','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('41','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('42','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('42','¿Con qué frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');
insert into scores (question_id,question_content,options,value) values ('42','¿Con qué frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('42','¿Con qué frecuencia se actualiza?','OTRO','1');	
insert into scores (question_id,question_content,options,value) values ('43','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('43','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('44','¿Los equipos de la compañía cuenta con el bloqueo de sesión automático ante inactividad?','SI','2');
insert into scores (question_id,question_content,options,value) values ('44','¿Los equipos de la compañía cuenta con el bloqueo de sesión automático ante inactividad?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('42','¿Después de qué periodo de inactividad se bloquea? (Minutos)','1','2');
insert into scores (question_id,question_content,options,value) values ('42','¿Después de qué periodo de inactividad se bloquea? (Minutos)','2','2');
insert into scores (question_id,question_content,options,value) values ('42','¿Después de qué periodo de inactividad se bloquea? (Minutos)','10','2');
insert into scores (question_id,question_content,options,value) values ('42','¿Después de qué periodo de inactividad se bloquea? (Minutos)','12','2');
insert into scores (question_id,question_content,options,value) values ('42','¿Después de qué periodo de inactividad se bloquea? (Minutos)','OTRO','1');
insert into scores (question_id,question_content,options,value) values ('46','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('46','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('47','¿Cuéntan con firewall configurado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('47','¿Cuéntan con firewall configurado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('46','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('46','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content) values ('48','¿De que tipo?');	
insert into scores (question_id,question_content,options,value) values ('49','¿Existe una regla dfault dny que impide el tráfico excepto el de los servicios o puertos permitidos?','SI','2');
insert into scores (question_id,question_content,options,value) values ('49','¿Existe una regla dfault dny que impide el tráfico excepto el de los servicios o puertos permitidos?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('20','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('20','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('21','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conecciones?','SI','2');
insert into scores (question_id,question_content,options,value) values ('21','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conecciones?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('22','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('22','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('23','¿Su pagina institucional utiliza certificado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('23','¿Su pagina institucional utiliza certificado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('24','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('24','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('22','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conecciones?','SI','2');
insert into scores (question_id,question_content,options,value) values ('22','¿Utiliza la empresa configuraciones seguras como protocolos SSH y VPN para las conecciones?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('26','¿Se cuenta con un inventario de cuentas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('26','¿Se cuenta con un inventario de cuentas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('27','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('27','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('28','¿Con qué frecuencia se actualiza?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('28','¿Con qué frecuencia se actualiza?','TRIMESTRAL/SEMESTRAL','1');
insert into scores (question_id,question_content,options,value) values ('28','¿Con qué frecuencia se actualiza?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('28','¿Con qué frecuencia se actualiza?','OTRO','1');	
insert into scores (question_id,question_content,options,value) values ('29','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('29','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('60','¿Cuentan con segundo factor de autentificacion en las cuentas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('60','¿Cuentan con segundo factor de autentificacion en las cuentas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('61','¿Las contraseñas utilizadas en la compañía tienen un minimo de 8 caracteres con+L39 2FA o 14 sin 2FA?','SI','2');
insert into scores (question_id,question_content,options,value) values ('61','¿Las contraseñas utilizadas en la compañía tienen un minimo de 8 caracteres con+L39 2FA o 14 sin 2FA?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('62','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('62','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('63','¿Las cuentas sin uso o "durmientes" son desacticvadas despues de 42 días sin actividad?','SI','2');
insert into scores (question_id,question_content,options,value) values ('63','¿Las cuentas sin uso o "durmientes" son desacticvadas despues de 42 días sin actividad?','NO','0');
insert into scores (question_id,question_content,options,value) values ('63','¿Las cuentas sin uso o "durmientes" son desacticvadas despues de 42 días sin actividad?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('64','¿Estas configuraciones están documentadas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('64','¿Estas configuraciones están documentadas?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('62','¿Tienen todos los dispositivos de usuario configurada la cuenta administrador?','SI','2');
insert into scores (question_id,question_content,options,value) values ('62','¿Tienen todos los dispositivos de usuario configurada la cuenta administrador?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('66','El uso diario de los equipos ¿es realizado desde la cuenta de usuario solamente?','SI','2');
insert into scores (question_id,question_content,options,value) values ('66','El uso diario de los equipos ¿es realizado desde la cuenta de usuario solamente?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('67','¿Tienen los administradores de red una cuenta en todos los equipos?','SI','2');
insert into scores (question_id,question_content,options,value) values ('67','¿Tienen los administradores de red una cuenta en todos los equipos?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('68','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','SI','2');
insert into scores (question_id,question_content,options,value) values ('68','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','NO','0');
insert into scores (question_id,question_content,options,value) values ('68','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('69','¿Este proceso es automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('69','¿Este proceso es automatizado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('70','¿Se sigue este proceso también para cambios de rol de un usuario?','SI','2');
insert into scores (question_id,question_content,options,value) values ('70','¿Se sigue este proceso también para cambios de rol de un usuario?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('71','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','SI','2');
insert into scores (question_id,question_content,options,value) values ('71','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','NO','0');
insert into scores (question_id,question_content,options,value) values ('71','¿Existe un proceso escrito de generación de cuenta ante una nueva contratación?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('72','¿Este proceso es automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('72','¿Este proceso es automatizado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('73','¿Se sigue este proceso también para cambios de rol de un usuario?','SI','2');
insert into scores (question_id,question_content,options,value) values ('73','¿Se sigue este proceso también para cambios de rol de un usuario?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('74','¿Existe esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('74','¿Existe esta configuración?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('72','¿Está documentada?','SI','2');
insert into scores (question_id,question_content,options,value) values ('72','¿Está documentada?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('76','¿Existe esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('76','¿Existe esta configuración?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('77','¿Está documentada?','SI','2');
insert into scores (question_id,question_content,options,value) values ('77','¿Está documentada?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('78','¿Existe esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('78','¿Existe esta configuración?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('79','¿Está documentada?','SI','2');
insert into scores (question_id,question_content,options,value) values ('79','¿Está documentada?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('80','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','SI','2');
insert into scores (question_id,question_content,options,value) values ('80','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','NO','0');
insert into scores (question_id,question_content,options,value) values ('80','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('81','¿Este proceso es automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('81','¿Este proceso es automatizado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('83','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','SI','2');
insert into scores (question_id,question_content,options,value) values ('83','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','NO','0');
insert into scores (question_id,question_content,options,value) values ('83','¿Existe un proceso escrito de gestión de vulnerabilidades de los dispositivos de la empresa?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('84','¿Este proceso es automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('84','¿Este proceso es automatizado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('82','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('86','¿Este proceso es automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('86','¿Este proceso es automatizado?','NO','0');		
insert into scores (question_id,question_content,options,value) values ('87','¿Se ha realizado esta implementacion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('87','¿Se ha realizado esta implementacion?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('88','¿Este proceso es automatizado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('88','¿Este proceso es automatizado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('89','¿Se ha realizado esta implementacion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('89','¿Se ha realizado esta implementacion?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('90','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('90','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('90','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('91','¿Existe un proceso escrito de gestión de logs de auditoria?','SI','2');
insert into scores (question_id,question_content,options,value) values ('91','¿Existe un proceso escrito de gestión de logs de auditoria?','NO','0');
insert into scores (question_id,question_content,options,value) values ('91','¿Existe un proceso escrito de gestión de logs de auditoria?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('92','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('92','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('92','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('92','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('93','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('93','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('93','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content) values ('94','¿Se cumple este punto?, ¿Cómo?');					
insert into scores (question_id,question_content,options,value) values ('95','¿Se hacen backups de los logs?','SI','2');
insert into scores (question_id,question_content,options,value) values ('95','¿Se hacen backups de los logs?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('96','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('96','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('96','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('97','¿Existe un proceso escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('97','¿Existe un proceso escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('98','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('98','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('98','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('98','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('99','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('99','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('99','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('100','¿Existe un proceso escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('100','¿Existe un proceso escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('101','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('101','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('101','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('101','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('102','¿Usa algun servicio de filtrado de DNS?','SI','2');
insert into scores (question_id,question_content,options,value) values ('102','¿Usa algun servicio de filtrado de DNS?','NO','0');
insert into scores (question_id,question_content,options,value) values ('102','¿Usa algun servicio de filtrado de DNS?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('103','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('103','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('103','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content) values ('104','¿Que Software ocupa la empresa?');					
insert into scores (question_id,question_content,options,value) values ('102','¿Existe un proceso escrito que detalle la configuracion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('102','¿Existe un proceso escrito que detalle la configuracion?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('106','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('106','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('106','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('106','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('107','¿Tiene su software anti-malware un sistema centralizado de administracion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('107','¿Tiene su software anti-malware un sistema centralizado de administracion?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('108','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('108','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('108','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('109','¿Existe un proceso escrito que detalle la configuracion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('109','¿Existe un proceso escrito que detalle la configuracion?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('110','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('110','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('110','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','2');
insert into scores (question_id,question_content,options,value) values ('110','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');	
insert into scores (question_id,question_content,options,value) values ('111','¿Se ha realizado esta configuración?','SI','2');
insert into scores (question_id,question_content,options,value) values ('111','¿Se ha realizado esta configuración?','NO','0');
insert into scores (question_id,question_content,options,value) values ('111','¿Se ha realizado esta configuración?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('112','¿Existe un proceso escrito que detalle la configuracion?','SI','2');
insert into scores (question_id,question_content,options,value) values ('112','¿Existe un proceso escrito que detalle la configuracion?','NO','0');		
insert into scores (question_id,question_content,options,value) values ('113','¿Cada cuanto se revisa el proceso?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('113','¿Cada cuanto se revisa el proceso?','MENSUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('113','¿Cada cuanto se revisa el proceso?','SEMESTRALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('113','¿Cada cuanto se revisa el proceso?','ANUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('114','¿Cuentan con un proceso de recuperación ante desastres escrito?','SI','2');
insert into scores (question_id,question_content,options,value) values ('114','¿Cuentan con un proceso de recuperación ante desastres escrito?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('112','¿Los respaldos son automatizados?','SI','2');
insert into scores (question_id,question_content,options,value) values ('112','¿Los respaldos son automatizados?','NO','0');
insert into scores (question_id,question_content,options,value) values ('112','¿Los respaldos son automatizados?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('116','¿Cada cuanto se realizan respaldos?','CONTINUAMENTE','2');
insert into scores (question_id,question_content,options,value) values ('116','¿Cada cuanto se realizan respaldos?','DIARIAMENTE','1');
insert into scores (question_id,question_content,options,value) values ('116','¿Cada cuanto se realizan respaldos?','SEMANALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('116','¿Cada cuanto se realizan respaldos?','MENSUALMENTE','1');
insert into scores (question_id,question_content,options,value) values ('116','¿Cada cuanto se realizan respaldos?','OTRO','0');
insert into scores (question_id,question_content,options,value) values ('117','¿Cuentan con respaldo en todas las maquinas?','SI','2');
insert into scores (question_id,question_content,options,value) values ('117','¿Cuentan con respaldo en todas las maquinas?','NO','0');			
insert into scores (question_id,question_content) values ('118','¿Que software ocupa la empresa?');					
insert into scores (question_id,question_content) values ('119','¿Los respaldos están protegidos en su proceso y en destino? ¿cómo?');
insert into scores (question_id,question_content) values ('119','¿Los respaldos están protegidos en su proceso y en destino? ¿cómo?');					
insert into scores (question_id,question_content) values ('121','¿Existe una destinación del respaldo que no esté conectada a la red / esté en la nube / o se encuentre en una ubicación distinta a la de la empresa?');					
insert into scores (question_id,question_content,options,value) values ('122','¿Cuentan con este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('122','¿Cuentan con este punto?','NO','0');
insert into scores (question_id,question_content,options,value) values ('122','¿Cuentan con este punto?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('123','¿Esta documentado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('123','¿Esta documentado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('123','¿Esta documentado?','OTRO','1');
insert into scores (question_id,question_content,options,value) values ('124','¿Se cuenta con un programa de concientización o capacitación en ciberseguridad?','SI','2');
insert into scores (question_id,question_content,options,value) values ('124','¿Se cuenta con un programa de concientización o capacitación en ciberseguridad?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('122','¿Está documentado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('122','¿Está documentado?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('126','¿Se rigen por un programa/plan externo o es realizado internamente?','Externo','2');
insert into scores (question_id,question_content,options,value) values ('126','¿Se rigen por un programa/plan externo o es realizado internamente?','Interno','1');		
insert into scores (question_id,question_content) values ('127','En caso de ser un programa o proveedor externo ¿Cuál?');					
insert into scores (question_id,question_content,options,value) values ('128','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('128','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('129','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('129','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('130','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('130','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('131','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('131','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('132','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('132','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('133','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('133','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('134','¿El programa incluye este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('134','¿El programa incluye este punto?','NO','0');			
insert into scores (question_id,question_content,options,value) values ('132','¿Cuentan con un inventario de proveedores de servicio?','SI','2');
insert into scores (question_id,question_content,options,value) values ('132','¿Cuentan con un inventario de proveedores de servicio?','NO','0');
insert into scores (question_id,question_content,options,value) values ('132','¿Cuentan con un inventario de proveedores de servicio?','OTRO','1');	
insert into scores (question_id,question_content,options,value) values ('136','¿Está documentado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('136','¿Está documentado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('136','¿Está documentado?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('137','¿Cuentan con personal designado?','SI','2');
insert into scores (question_id,question_content,options,value) values ('137','¿Cuentan con personal designado?','NO','0');
insert into scores (question_id,question_content,options,value) values ('137','¿Cuentan con personal designado?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('138','¿Es conocido por toda la organización?','SI','2');
insert into scores (question_id,question_content,options,value) values ('138','¿Es conocido por toda la organización?','NO','0');
insert into scores (question_id,question_content,options,value) values ('138','¿Es conocido por toda la organización?','OTRO','1');
insert into scores (question_id,question_content,options,value) values ('139','¿Cuenta toda la organización con esta información?','SI','2');
insert into scores (question_id,question_content,options,value) values ('139','¿Cuenta toda la organización con esta información?','NO','0');
insert into scores (question_id,question_content,options,value) values ('139','¿Cuenta toda la organización con esta información?','OTRO','1');		
insert into scores (question_id,question_content,options,value) values ('140','¿Se cuenta con un procedimiento escrito que relate este punto?','SI','2');
insert into scores (question_id,question_content,options,value) values ('140','¿Se cuenta con un procedimiento escrito que relate este punto?','NO','0');
insert into scores (question_id,question_content,options,value) values ('140','¿Se cuenta con un procedimiento escrito que relate este punto?','OTRO','1');

select * from scores;
